E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<353> : u'-be-'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<341> : u'\u201d'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<362> : u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<362> : u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<362> : u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<362> : u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<362> : u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<362> : u'\x0c'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'E:\Documents\1. Belajar\AI\Phyton\pybrl-master\pybrl.py<356> : An exception occured while handling exception `u'\n\n\x0c-'`. 
Error message: u'\n'